# 开发环境配置

version: "3"
services:
    ui:
        container_name: "yraid_ui"
        build: ./ui/
        restart: unless-stopped
        environment:
            TZ: "Asia/Shanghai"
        ports:
            - "10102:5173"
        volumes: 
            - "./:/app"
            - "/etc/localtime:/etc/localtime:ro"
        working_dir: "/app/ui/"
        entrypoint: "/bin/sh entrypoint.sh"
        tty: true
        depends_on:
            - server

    server:
        container_name: "yraid_server"
        build: ./server/
        restart: unless-stopped
        environment:
            BASEPATH: "/"
            GOPROXY: https://goproxy.cn
        ports:
            - "10104:1625"
        volumes:
            - "./:/app"
            - "/etc/localtime:/etc/localtime:ro"
        working_dir: "/app/server"
        entrypoint: "/bin/sh entrypoint.sh"
        tty: true
