# 正式环境配置

version: '3'
services:
    yraid:
        container_name: yraid
        build: 
          context: .
          args:
            BASEPATH: / # base path for ui and server, cannot change on the fly cause of embedding ui
        #restart: unless-stopped
        working_dir: "/app/"
        environment:
            GIN_MODE: release
        entrypoint: "yraid --port=1625"
        volumes:
            - "./.data:/app/.data"
        ports:
            - 1625:1625
        
        tty: true