# docsify 文档镜像

version: "3"
services:
  doc:
    container_name: "yraid_doc"
    build: .
    volumes: 
      - "./:/app/docs"
    working_dir: "/app/docs"
    entrypoint: "docsify serve ."
    restart: unless-stopped
    tty: true

    networks:
      - pronet

networks:
  pronet:
    name: pro_net
